# Generated by Django 4.1.3 on 2022-12-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="ctr",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="link",
            name="username",
            field=models.CharField(default="xxx", max_length=2083),
        ),
    ]
