# Generated by Django 4.1.3 on 2024-11-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortner", "0002_link_ctr_link_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="possibly_malicious",
            field=models.BooleanField(default=False),
        ),
    ]
