# Generated by Django 4.1.3 on 2024-11-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortner", "0003_link_possibly_malicious"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="virus_total_analysis_id",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
