# Generated by Django 4.1.3 on 2024-11-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortner", "0004_link_virus_total_analysis_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="link",
            name="virus_total_analysis_id",
        ),
        migrations.AddField(
            model_name="link",
            name="vt_analysis_id",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="link",
            name="vt_analysis_stats",
            field=models.JSONField(null=True),
        ),
    ]
